# Generated by Django 2.2.6 on 2020-04-24 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True,
                                        serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=500,
                                            unique=True, verbose_name='NOMBRE ')),
                ('ap', models.CharField(max_length=500,
                                        verbose_name='APELLIDO PATERNO ')),
                ('am', models.CharField(max_length=500,
                                        verbose_name='APELLIDO MATERNO ')),
                ('domicilio', models.CharField(
                    max_length=500, verbose_name='DOMICILIO')),
                ('colonia', models.CharField(max_length=500, verbose_name='COLONIA')),
                ('telefono', models.CharField(
                    max_length=15, verbose_name='TELEFONO')),
                ('fn', models.DateField(verbose_name='FECHA DE NACIMIENTO')),
                ('ga', models.CharField(choices=[('PRIMARIA', 'PRIMARIA'), ('SECUNDARIA', 'SECUNDARIA'), ('PREPA', 'PREPA'), (
                    'UNIVERSIDAD', 'UNIVERSIDAD')], default='PRIMARIA', max_length=50, verbose_name='GRADO ACADEMICO')),
                ('matricula', models.CharField(
                    max_length=50, verbose_name='MATRICULA')),
                ('formacion_artistica', models.CharField(choices=[('ARTES PLASTICAS', 'ARTES PLASTICAS'), ('MUSICA', 'MUSICA'), ('DANZA', 'DANZA'), (
                    'TEATRO', 'TEATRO'), ('LITERATURA', 'LITERATURA')], default='MUSICA', max_length=50, verbose_name='FORMACIÓN ARTISTICA')),
                ('modalidad', models.CharField(choices=[('APROVECHAMIENTO ESCOLAR', 'APROVECHAMIENTO ESCOLAR'), (' APROVECHAMIENTO ACADEMICO DESTACADO', 'APROVECHAMIENTO ACADEMICO DESTACADO'), (
                    'APOYO ALUMNOS FORANEOS', 'APOYO ALUMNOS FORANEOS')], default='APROVECHAMIENTO ESCOLAR', max_length=500, verbose_name='MODALIDAD DE BECA')),
                ('genero', models.CharField(choices=[('MASCULINO', 'MASCULINO'), (
                    'FEMENINO', 'FEMENINO')], default='FEMENINO', max_length=500, verbose_name='GENERO')),
                ('correo', models.EmailField(
                    max_length=254, verbose_name='CORREO ELECTRONICO')),
                ('entrega', models.CharField(blank=True, choices=[('ENTREGADO', 'ENTREGADO'), (
                    'NO ENTREGADO', 'NO ENTREGADO')], default='NO ENTREGADO', max_length=50, verbose_name='ESTADO DEL APOYO')),
            ],
        ),
    ]
